### ISSUE TITLE
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead. 

### ISSUE THREAD

**Issue by rahulvageriya** [brightlayer-ui/react-native-component-library#245] opened 2022-02-22 11:47 UTC
When We are trying to use Flat list under CollapsibleHeaderLayout  , we were getting below console error:

VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.

**Comment by jeffvg** [comment] 2022-02-22 14:36
thank you for submitting this issue. This is duplicate of https://github.com/brightlayer-ui/react-native-component-library/issues/218
and should be available in an updated release of react native components version 6.1.0

**Closed by jeffvg** 2022-02-22 14:36 UTC
Labels: bug, needs-review, user-reported
